#!/bin/bash                                                     
                                                                                             
vim -c 12131,15945s/ENCODER1/ENCODER34/g /mnt/c/Users/fakuve/Desktop/kaka
vim -c 12131,15945s/ENCODER1/ENCODER35/g /mnt/c/Users/fakuve/Desktop/kaka
vim -c 12131,15945s/ENCODER1/ENCODER36/g /mnt/c/Users/fakuve/Desktop/kaka
vim -c 12131,15945s/ENCODER1/ENCODER37/g /mnt/c/Users/fakuve/Desktop/kaka
vim -c 12131,15945s/ENCODER1/ENCODER38/g /mnt/c/Users/fakuve/Desktop/kaka
vim -c 12131,15945s/ENCODER1/ENCODER39/g /mnt/c/Users/fakuve/Desktop/kaka
vim -c 12131,15945s/ENCODER1/ENCODER40/g /mnt/c/Users/fakuve/Desktop/kaka
vim -c 12131,15945s/ENCODER1/ENCODER41/g /mnt/c/Users/fakuve/Desktop/kaka
vim -c 12131,15945s/ENCODER1/ENCODER42/g /mnt/c/Users/fakuve/Desktop/kaka
vim -c 12131,15945s/ENCODER1/ENCODER43/g /mnt/c/Users/fakuve/Desktop/kaka
